import { BookOpen, Check, ListChecks } from 'lucide-react'
import type { Problem } from '../types'

export function ProblemDescription({ problem }: { problem: Problem }) {
  return <section className="min-w-0 rounded-2xl border border-white/[0.08] bg-[#101722] p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#55d6be]">Challenge {String(problem.id).padStart(2, '0')}</p><h1 className="mt-2 text-2xl font-bold tracking-tight text-white sm:text-3xl">{problem.title}</h1></div><div className="flex gap-2"><span className="rounded-md border border-[#55d6be]/25 bg-[#55d6be]/10 px-2.5 py-1 text-xs font-semibold text-[#71e0cb]">{problem.difficulty}</span><span className="rounded-md border border-white/10 bg-white/[0.04] px-2.5 py-1 text-xs text-slate-300">{problem.topic}</span></div></div>
    <div className="mt-7 flex items-center gap-2 border-b border-white/[0.08] pb-3 text-sm font-semibold text-slate-200"><BookOpen size={16} className="text-[#55d6be]" />Problem brief</div><p className="mt-5 text-sm leading-7 text-slate-300">{problem.description}</p>
    <div className="mt-7 grid gap-4 sm:grid-cols-2">{problem.examples.map((example, index) => <div key={example.input} className="rounded-xl border border-white/[0.07] bg-[#0b111a] p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">Example {index + 1}</p><div className="mt-3 space-y-2 font-mono text-xs"><p><span className="text-slate-500">Input</span> <span className="text-[#a8b8cc]">{example.input}</span></p><p><span className="text-slate-500">Output</span> <span className="text-[#8de8d7]">{example.output}</span></p></div><p className="mt-3 text-xs leading-5 text-slate-500">{example.explanation}</p></div>)}</div>
    <div className="mt-7"><div className="flex items-center gap-2 text-sm font-semibold text-slate-200"><ListChecks size={16} className="text-[#55d6be]" />Constraints</div><ul className="mt-3 space-y-2">{problem.constraints.map((constraint) => <li key={constraint} className="flex gap-2 text-xs leading-5 text-slate-400"><Check size={14} className="mt-0.5 shrink-0 text-slate-600" />{constraint}</li>)}</ul></div>
  </section>
}
