import { ArrowLeft, CheckCircle2, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { CodeEditor } from '../components/CodeEditor'
import { MentorChat } from '../components/MentorChat'
import { ProblemDescription } from '../components/ProblemDescription'
import { runCode } from '../services/codeService'
import type { Feedback, Problem as ProblemType, TestResult } from '../types'

export function Problem({ problem, onBack }: { problem: ProblemType; onBack: () => void }) {
  const [code, setCode] = useState(problem.starterCode); const [running, setRunning] = useState(false); const [analyzing, setAnalyzing] = useState(false); const [results, setResults] = useState<TestResult[]>([]); const [feedback, setFeedback] = useState<Feedback | null>(null)
  const execute = async () => { setRunning(true); setResults([]); setResults(await runCode()); setRunning(false) }
  const analyze = async () => { setAnalyzing(true); await new Promise((resolve) => setTimeout(resolve, 750)); setFeedback({ correctness: 'Your solution correctly identifies the required pair for the shown test cases.', timeComplexity: 'O(n²) with the brute-force nested-loop approach.', spaceComplexity: 'O(1) auxiliary space.', codeQuality: 'The structure is easy to follow and the function has a focused responsibility.', improvement: 'You can reduce lookup time by storing previously visited values in a HashMap.', nextStep: 'Can you think of what key and value you would store for each visited number?' }); setAnalyzing(false) }
  return <main className="mx-auto max-w-[1440px] px-5 pb-16 pt-6 lg:px-8"><button onClick={onBack} className="mb-6 flex items-center gap-2 text-sm font-semibold text-slate-500 transition hover:text-white"><ArrowLeft size={16} />Back to problems</button><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_430px]"><ProblemDescription problem={problem} /><MentorChat problem={problem} /></div><div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_430px]"><div><CodeEditor code={code} onChange={setCode} onRun={() => void execute()} onFeedback={() => void analyze()} running={running} analyzing={analyzing} />{results.length > 0 && <section className="mt-5 rounded-2xl border border-[#55d6be]/20 bg-[#101722] p-5"><div className="flex items-center gap-2"><CheckCircle2 size={18} className="text-[#55d6be]" /><h2 className="font-semibold text-white">Test results</h2><span className="text-xs text-slate-500">Mock evaluation</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{results.map((result) => <div key={result.title} className="rounded-xl border border-white/[0.08] bg-[#0b111a] p-4"><p className="text-sm font-semibold text-[#71e0cb]">✓ {result.title}</p><div className="mt-3 space-y-1 font-mono text-xs"><p><span className="text-slate-600">input</span> <span className="text-slate-400">{result.input}</span></p><p><span className="text-slate-600">expected</span> <span className="text-slate-400">{result.expected}</span></p><p><span className="text-slate-600">output</span> <span className="text-[#8de8d7]">{result.output}</span></p></div></div>)}</div></section>}</div><aside>{feedback ? <section className="rounded-2xl border border-[#f1b962]/20 bg-[#101722] p-5"><div className="flex items-center gap-2"><Sparkles size={18} className="text-[#f1c978]" /><h2 className="font-semibold text-white">AI feedback</h2></div><p className="mt-1 text-xs text-slate-500">A nudge toward your next improvement.</p><div className="mt-6 space-y-4">{Object.entries(feedback).map(([label, value]) => <div key={label}><p className="text-xs font-semibold capitalize text-slate-300">{label === 'nextStep' ? 'Next step' : label.replace(/([A-Z])/g, ' $1')}</p><p className="mt-1 text-xs leading-5 text-slate-500">{value}</p></div>)}</div></section> : <div className="flex min-h-[220px] flex-col justify-center rounded-2xl border border-dashed border-white/10 bg-[#101722] p-6 text-center"><Sparkles className="mx-auto text-slate-600" size={24} /><h2 className="mt-4 text-sm font-semibold text-slate-300">Your feedback will appear here</h2><p className="mt-2 text-xs leading-5 text-slate-500">Write a first attempt, run it, then ask your mentor to review your thinking.</p></div>}</aside></div></main>
}
